# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

# Use the correct URL for your private repository
source 'https://cdn.cocoapods.org/'
source 'https://github.com/Umang-Reformiqo-2024/workspace.git'

target 'Runner' do
  use_frameworks!

  # Pods for Runner
  pod 'motion' # Ensure this is the correct pod name

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
      end
    end
  end
end
