name: iOS-ipa-build-dart

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Set up Flutter environment
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      
      # Get Flutter dependencies
      - run: flutter pub get

      # Update CocoaPods repository
      - run: pod repo update
        working-directory: ios

      # Build the iOS app without code signing
      - run: flutter build ios --release --no-codesign

      # Create Payload directory
      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      # Move the built app to the Payload directory
      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      # Zip the Payload directory into an .ipa file
      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      # Upload the .ipa file to the GitHub release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: 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
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
